name: Citations
# A workflow that fetches the citation counts from semantic scholar and compares
# them to the stored citations.

on:
  schedule:
    # Now that live data API is so limited, we want to get the new citations
    # and rebuild/deploy the site more often. Once an hour.
    - cron: "0 * * * *"
  # Enable manually triggering from GitHub.
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Fetch Citations
        env:
          SEMANTIC_SCHOLAR_API_KEY: ${{ secrets.SEMANTIC_SCHOLAR_API_KEY }}
        run: |
          pip install requests
          python3 citations.py static/references/references.json
      - name: Prettify Citations
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write static/references/references.json
