name: Copyright
# A workflow that updates the current year in the copyright notice on my site.

on:
  schedule:
    # Now that live data API is so limited, we want to get the new citations
    # and rebuild/deploy the site more often. Once an hour.
    - cron: "0 0 1 1 *"
  # Enable manually triggering from GitHub.
  workflow_dispatch:

jobs:
  copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Update Copyright
        run: |
          python3 update-copyright.py
      - name: Prettify Footer
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write static/footer.html
